name: python-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Use predefined action to checkout repository
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
    # Use of a multi-line command to first install pip and then requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # Any return that is non-zero will terminate the job
    # Linting could be added here to terminate before running tests in case of linting errors
    - name: Test with unittest
      run: |
        python3 character/test_character.py